name: Deploy from Release Assets

on:
  release:
    types:
      - published

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Download release asset (api-build.zip)
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: api-build.zip
          out-file-path: artifact

      - name: Verify asset
        run: |
          echo "Downloaded assets:"
          ls -la artifact

      - name: Extract build
        run: |
          unzip artifact/api-build.zip -d artifact

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV"
          ls -la artifact


  deploy-prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Download release asset (api-build.zip)
        uses: robinraju/release-downloader@v1.9
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: api-build.zip
          out-file-path: artifact

      - name: Extract build
        run: |
          unzip artifact/api-build.zip -d artifact

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD"
          ls -la artifact
